name = "tabora-api"
main = "index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "tabora"
database_id = "95b27545-ccfe-43b8-aa81-7bdd859313ac"

[vars]
OWNER_EMAIL = ""
